### ISSUE TITLE
Accents issue

### ISSUE THREAD

**Issue by maganius** [artesaos/seotools#116]
I have a problem with accent it's not displayed correctly.

Example:

This is before setDescription:
público

This is after I setDescription:
p&uacute ;blico -> the space is because this editor set correctly the accent

The correct is the first line: público

How I can fix this?

**Comment by isneezy** [comment]
Please make sure you're using ``{!! SEO::generate() !!}`` insted of ``{{ SEO::generate() }}``

**Comment by yakuter** [comment]
I have the same problem and {!! SEO::generate() !!} didn't solve it. Do you have any idea? 

If I write {{ $website->meta_description }} it gets from db normally as normal (ççşşğğ) however when I use SEOMeta::setDescription($website->meta_description); result is (&ccedil;&ccedil;şşğğ). 

{!! SEO::generate() !!} didn't work for me

**Comment by isneezy** [comment]
@yakuter I didnt get your problem! But can your post the output of ``{!! SEO::generate() !!}``?

**Comment by woliveirac** [comment]
Hi @yakuter and @isneezy , his problem is this:

He's trying to put 'characters with accents' as descriptions in the metatags and he's getting error with its charset because of this:

/**
     * @param string $description
     *
     * @return MetaTagsContract
     */
    public function setDescription($description)
    {
        // clean and store description
        // if is false, set false
        $this->description = (false == $description) ? $description : strip_tags(htmlentities($description));

        return $this;
    }

That's vendor/artesaos/seotools/src/SEOTools/SEOMeta.php:251 , there you do "htmlentities" of $description ... therefore, if your $description is something like this: 

$description = "Você terá problemas com acentos"; , when you use htmlentities() on that string, you get:

"Voc&ecirc; ter&aacute; problemas com acentos" 

I'm not sure of why that is happening, so, if you have an idea, please, let me know :) 

If you change that part of the code and remove htmlentities of that function, it's working just fine. 

I'll send you screenshots to be more clear. 

![screenshot_1](https://user-images.githubusercontent.com/7048196/43741488-edbf26d6-99a4-11e8-83cd-41f0ef1b9e23.png)
![result-seo-meta](https://user-images.githubusercontent.com/7048196/43741489-ede20d68-99a4-11e8-84d7-68619a74d0a8.png)
![removed_html_entities](https://user-images.githubusercontent.com/7048196/43741490-ee115866-99a4-11e8-9b56-58c012578c54.png)


i'm not sure if the "htmlentities" is the problem here, but, i think we should just try it, just in case. 

Composer json is:

"require": {
        "php": ">=7.0.0",
        "artesaos/seotools": "^0.12.0",
        "doctrine/inflector": "~1.2",
        "encore/laravel-admin": "^1.5",
        "fideloper/proxy": "~3.3",
        "laravel/framework": "5.5.*",
        "laravel/tinker": "~1.0"
    },


BTW, that's brazilean portuguese words.

Thank you :)

**Comment by reasecret** [comment]
I've charset problem too. Some Turkish characters not showing properly. {!! SEO::generate() !!} not working and @woliveirac 's solution didn't solve problem for me...

**Comment by vinicius73** [comment]
Fixed in #159
