### ISSUE TITLE
Can't install on Laravel 5.7

### ISSUE THREAD

**Issue by captenmasin** [artesaos/seotools#124]
Keep getting this error, this only happens with this package and 2 others... Any ideas?

  Problem 1
    - Installation request for artesaos/seotools ^0.12.0 -> satisfiable by artesaos/seotools[v0.12.0].
    - Conclusion: remove laravel/framework v5.7.0
    - Conclusion: don't install laravel/framework v5.7.0
    - artesaos/seotools v0.12.0 requires illuminate/support 5.0.* || 5.1.* || 5.2.* || 5.3.* || 5.4.* || 5.5.* || 5.6.* -> satisfiable by laravel/framework[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev], illuminate/support[5.0.x-dev, 5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - Can only install one of: laravel/framework[5.5.x-dev, v5.7.0].
    - Can only install one of: laravel/framework[5.6.x-dev, v5.7.0].

**Comment by rjsworking** [comment]
There's a PR to fix this issue waiting to be mergerd.

**Comment by sajjad-talebi** [comment]
Same issue

**Comment by ricardocanelas** [comment]
+1

**Comment by lionskape** [comment]
Same issue

**Comment by SpikeDieHard** [comment]
I got mine installed with the version mentioned by @warmwhisky.
Partial Output from Composer show -i
artesaos/seotools                     v0.12.1  SEO Tools for Laravel and Lumen

However I get the following error when trying to implement:
Uncaught ReflectionException: Class view does not exist in /home/xxxx/xxxx/vendor/laravel/framework/src/Illuminate/Container/Container.php:779
ERROR: Class 'Artesaos\SEOTools\Providers\SEOToolsServiceProvider

Any insights?

**Comment by warmwhisky** [comment]
> Uncaught ReflectionException: Class view does not exist in

I can't recall how I got this going now. But I think I manually added the class `Artesaos\SEOTools\Providers\SEOToolsServiceProvider::class,` the the providers array in config/app and also `'SEO' => Artesaos\SEOTools\Facades\SEOTools::class,` to the aliases array.

**Comment by SpikeDieHard** [comment]
> > Uncaught ReflectionException: Class view does not exist in
> 
> I can't recall how I got this going now. But I think I manually added the class `Artesaos\SEOTools\Providers\SEOToolsServiceProvider::class,` the the providers array in config/app and also `'SEO' => Artesaos\SEOTools\Facades\SEOTools::class,` to the aliases array.

It seems I have it going fine.  I forgot the issue only occurs when I move the app to prod, but it does run on shared hosting, so it might that.  On a local server it runs fine.  Will see when I run it on a prod server with the same setup I have in dev.  I am new to Laravel, so still trying to find my way around things.  So what I have is a \routes\web.php which typically contains a route such as this:
`Route::name('about')->get('/about', 'PagesController@about');`
Then in the NS I have:
App\Http\Controllers\PagesController

I believe my issue creeps in here somewhere with the namespacing at the top.  So as a stock controller made with php artisan make:controller the defaults I get are:

namespace App\Http\Controllers;
use Illuminate\Http\Request;

Additionally I add the following lines since I can see that it loads with psr4 autoloader 'Artesaos\\SEOTools\\' => array($vendorDir . '/artesaos/seotools/src/SEOTools'),
use SEO;
use SEOMeta;
use OpenGraph;

In the method "about" I then have this:

`		
$description = 'Some text goes here to describe';
SEOMeta::setTitle('Set the title here')
            ->setDescription($description);
		SEO::setTitle('Set the title here');
               SEO::setDescription($description);`

Then in the blade view I use {!! SEOMeta::generate() !!}

**Comment by vinicius73** [comment]
Is this still a problem?

**Comment by claide** [comment]
Laravel 5.7 yes still an issue seotools 0.18.0

**Comment by Obistar** [comment]
You can simply fix that by providing the compatible version 0.12.1 like this :
`composer require artesaos/seotools:0.12.1`
This work with Laravel 5.7.x.
