### ISSUE TITLE
Canoncial URL should use Url::current() instead of Url::full()

### ISSUE THREAD

**Issue by chescos** [artesaos/seotools#180]
When setting the config option `meta.defaults.canonical` to `null`, the canonical URL will be set from the value of `Url::full()` instead of `Url::current()`. `Url::full()` includes query parameters and the canonical URL is usually used to strip away query parameters like UTM tags, search parameters, and so on.

I mean, what's even the point of specifying a canonical URL from the full URL? That's exactly the same result as not setting a canonical URL at all.

**Comment by robinparisi** [comment]
Indeed, the current use of Url::full() bring no benefit for SEO since it will just use the full URL and generate a lot of duplicate content.

Expected behaviour (current page => canonical URL):

https://example.com?utm_source=email => https://example.com
https://example.com/products?filter=asc => https://example.com/products
https://example.com/page?I_will_harm_your_SEO => https://example.com/page

This is the best default behavior because all important parameters for SEO should preferably use URL rewriting (so compatible with Url::current())

**Comment by J-Brk** [comment]
XSS #247

**Comment by Barcelonczyk** [comment]
I totally agree that using Url::full() has no benefit for SEO. 

It's worth mentioning that the config file is inconsistent in the current situation:
https://github.com/artesaos/seotools/blob/ca27cd0edf917e0bc805227013859b8b5a1f01fb/src/resources/config/seotools.php#L17
https://github.com/artesaos/seotools/blob/ca27cd0edf917e0bc805227013859b8b5a1f01fb/src/resources/config/seotools.php#L41

Based on the config file both opengraph url and canonical should use Url::current() but in fact, only opengraph url does it.

So using the same config for opengraph url and canonical we will receive e.g.
<link rel="canonical" href="https://cms.test/foo?bar=baz "/>
<meta property="og:url" content="https://cms.test/foo" />

**Comment by vinicius73** [comment]
Fixed on #256
