### ISSUE TITLE
{{SEOMeta::getKeywords()}} doesnt work in blade.php

### ISSUE THREAD

**Issue by EPInformatyka** [artesaos/seotools#254]
1 - If i use  in my blade.php <meta itemprop="keywords" content="{{SEOMeta::getKeywords()}}"> then retrun htmlspecialchars() expects parameter 1 to be string, array given.

2 - if i use in my blade.php {!! SEOMeta::generate() !!} then meta keywords return ok 

I need use in my project no. 1 - how fixed this error

**Comment by J-Brk** [comment]
Please use the issue template instead of putting half of the information in the title and the other half in the content.

### What steps will reproduce the problem?
Use `SEOMeta::getKeywords()` in the Laravel blade template.

### What is the expected result?
Retrieving the keywords.

### What do you get instead?
Fatal error "htmlspecialchars() expects parameter 1 to be string, array given".

### Additional info

| Q                         | A
| ------------------------- | ---
| This Package Version      | v0.20.1
| Laravel Framework Version | 8.0
| PHP version               | 7.4.21
| Operating system          | CentOS

**Comment by J-Brk** [comment]
Issue confirmed.

**Comment by J-Brk** [comment]
It is indeed not clear from the documentation that it returns an array instead of an string.
This is not an bug. If you want to print it in your blade you will have to convert it.

`{{ implode(', ', SEOMeta::getKeywords()) }}`
