### ISSUE TITLE
Set the title dynamically

### ISSUE THREAD

**Issue by MahbodHastam** [artesaos/seotools#278]
How do I set the website title dynamically from the database or another config file?
`SeoTools::setTitle()` only changes the page title

**Comment by J-Brk** [comment]
By integrating `SeoTools::setTitle()` into your application and using the generator in the blade as explained in the documentation. Closing this issue since it's not an issue with this package.

**Comment by Rattone** [comment]
I'm reopening this issue because I believe that the problem is in changing the "title" (e.g. site name) positioned after the separator.
I'm having the same problem, I would like to dynamically change the "seotools.meta.defaults.title" config.
I can do it in service provider but I can't do it in middleware or controller.
If this is not possible I will have to manage this manually for each page
