### ISSUE TITLE
do this package can cache result

### ISSUE THREAD

**Issue by vahidalvandi** [artesaos/seotools#314]
hi
i want to use {!! SEO::generate() !!} in head of layout file , but i have question Can this code cache the results?

**Comment by almamund** [comment]
I'm here for the same answer.

**Comment by J-Brk** [comment]
How much do you want to cache? Since this package's performance penalty is so insignificant; I don't think you will be able to gain much performance by caching it's output. Like most Laravel packages it doesn't have any additional caching functionalities implemented. But it is compatible with Laravel view & config cache. 

You can always wrap it in your own caching implementation however but I don't think this is worth it.
