### ISSUE TITLE
Itemprop

### ISSUE THREAD

**Issue by ItsLhoudini** [artesaos/seotools#75]
Hi,

is it possible to implement the itemprop meta? Like:

SEOitemProp::name('Hello world!');
SEOitemProp::description('A new description');

and so on?

**Comment by paulofreitas** [comment]
Just to add here, since it's an interesting feature request...

The `itemprop` attribute is part of the WHATWG Microdata specification draft for semantic web: https://html.spec.whatwg.org/multipage/microdata.html and https://www.w3.org/TR/microdata/ :+1:

So it should be called Microdata and its API could use something like `Microdata::addProperty('name', 'Hello world!')` to render a `<meta itemprop="name" content="Hello world!">` meta tag. 😀 

BTW it's the recommended snippet on Google+ platform, as [documented here](https://developers.google.com/+/web/snippet/) &ndash; it's allowed to use just `<meta>` tags, as [exemplified here](https://github.com/joshbuchea/HEAD#google--schemaorg).

Hope I've added something useful. :)

**Comment by paulofreitas** [comment]
BTW this could be merged with #71, both proposals are looking for Microdata implementation. :+1:

**Comment by m3chas** [comment]
Any updates on this feature?

**Comment by klimov-paul** [comment]
Microdata markup is nearly outdated nowadays.
Today 'JSON Linked Data' is recommended to be used instead.
Even examples at https://schema.org contains 'json-ld' snippets as an alternative to 'itemprop' usage.
`JsonLd` support is already provided by this extension.

Using microdata markup usually relates to internal HTML (e.g. contained in 'body' tag not 'head'), which is better to be control as any other markup.

I consider this issue can be closed.

**Comment by vinicius73** [comment]
Closed by #176
